site_name: DeepFold_DB_docs
theme:
  name: material
nav:
  - Home: index.md
  - gcputils: 
    - page: gcputils/gcputils.md
    - bigquery:
      - BigQueryManager: gcputils/bigquery/BigQueryManager.md
    - test:
      - connection_test: gcputils/test/connection_test.md
