theme:
  name: material
site_name: DeepFold_DB_docs
nav:
    - Home: index.md
    - gcputils:
        - BigQueryManager: gcputils/bigquery/BigQueryManager.md
        - gsutils: gcputils/gsutils.md
        - Test:
            - Connection Test: gcputils/test/connection_test.md